### ISSUE TITLE
Document server moderation tools (sv_rcon_mod_password)

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/documentation#26]

**Comment by Dune-jr** [comment]
Relevant code:

https://github.com/teeworlds/teeworlds/blob/37355c3961d9ad7b5f165088fc859a3ba449dcb1/src/engine/server/server.cpp#L1711

https://github.com/teeworlds/teeworlds/blob/37355c3961d9ad7b5f165088fc859a3ba449dcb1/src/engine/shared/console.cpp#L684-L685

https://github.com/teeworlds/teeworlds/blob/37355c3961d9ad7b5f165088fc859a3ba449dcb1/src/engine/shared/config_variables.h#L80

**Comment by Robyt3** [comment]
I think this was also fixed by #45.
