### ISSUE TITLE
Proposal: Rearrange docs, make them more visible

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/documentation#28]
I haven't figured where the docs were located for most of my stay on the forum. I once saw it linked somewhere but never could find it back. This is because the link to the actual documentation index is buried in "Support".

Here is a proposal.

- Merge [Support](https://www.teeworlds.com/?page=help) with [Documentation](https://www.teeworlds.com/?page=docs&wiki=docs_overview)

What it would look like:
![image](https://user-images.githubusercontent.com/355114/51540532-f18bc300-1e56-11e9-9b7e-913604796f2e.png)

I believe it would be much more visible that way, more people would be aware of the existence of site docs,  and there would still be the "search the FAQ first" message.

PS: header levels need to be adjusted

**Comment by Sonix-** [comment]
👍  support the proposal

**Comment by Dune-jr** [comment]
Thoughts, @oy ?

**Comment by oy** [comment]
Yeah, sounds good to me 👍
