### ISSUE TITLE
Nomenclature: enum prefix E

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/documentation#37]
`CUI::EAlignment` uses the E prefix to signal an `enum`, should be added to the documentation

**Comment by fokkonaut** [comment]
*should be used everywhere

**Comment by Dune-jr** [comment]
@oy thoughts?

**Comment by Ryozuki** [comment]
I don't think we should use a prefix for enums, looks really bad imho.

**Comment by oy** [comment]
@Dune-jr hm, not sure if we should enforce that prefix. Readability might suffer if we overdo things.

**Comment by Dune-jr** [comment]
Alright, so we keep the status quo
